### ISSUE TITLE
EMAL Blast genome database ID formatting issue

### ISSUE THREAD

**Issue by sib0** [dekoning-lab/ezmap#4]
Hello,

I encountered an issue while trying to set up ezmap to perform some tests.
I did not use your setup to get around sudo restrictions of my workstation and tried to run the pipeline in desktop mode on the sample fastq you're providing but EMAL returned the following error:

"Staring Step 5 - EMAL PREP\n\n
Determining Genebank ID and Calculating Genome Lengths.....
Traceback (most recent call last):
  File "/ezmap/tools/EMAL/EMAL-DataPrep.py", line 176, in <module>
    getNucleotideIDs(blastGenomeDBPath)
  File "/ezmap/tools/EMAL/EMAL-DataPrep.py", line 37, in getNucleotideIDs
    nucleotideID = line.split('|')[1]
IndexError: list index out of range"

It seems to expect fasta headers informations delimited by "|" in the blast genome database which isn't the case in the viral.1.1.genomic.fna file indicated in your wiki. A similar issue is returned during the EMAL Main step. Thank you for your assistance.

**Comment by rblawid** [comment]
Hi,

I do believe I have a similar error as sib0,

"File "/home/rb/EzMap/ezmap-master/tools/EMAL/EMAL-Main.py", line 400, in <module>
    information, genomeTaxon, totalNumberOfReads, blastHits = gatherInformation(BLASTFileArray)
  File "/home/rb/EzMap/ezmap-master/tools/EMAL/EMAL-Main.py", line 157, in gatherInformation
    genomeID = int(linePar[1].split('|')[1])
IndexError: list index out of range"

Thanks a lot for your help,

**Comment by LCarioti** [comment]
same problem

"Staring Step 5 - EMAL PREP\n\n
Determining Genebank ID and Calculating Genome Lengths.....
Traceback (most recent call last):
  File "/home/v/EzMap/tools/EMAL/EMAL-DataPrep.py", line 176, in <module>
    getNucleotideIDs(blastGenomeDBPath)
  File "/home/v/EzMap/tools/EMAL/EMAL-DataPrep.py", line 37, in getNucleotideIDs
    nucleotideID = line.split('|')[1]
IndexError: list index out of range
Staring Step 6 - EMAL MAIN\n\n

EMAL 0.2b 

Number of Threads: 16
Acceptance Value: 0.0001
Grabbing list of files to process from:
/home/v/EzMap/Output1/4-OrganismMapping/
1 files found to process:
/home/v/EzMap/Output1/4-OrganismMapping/SRR102448-PreSelectedReadsExample100KReads-blastn.tsv
Preparing to run...
Traceback (most recent call last):
  File "/home/v/EzMap/tools/EMAL/EMAL-Main.py", line 400, in <module>
    information, genomeTaxon, totalNumberOfReads, blastHits = gatherInformation(BLASTFileArray)
  File "/home/v/EzMap/tools/EMAL/EMAL-Main.py", line 157, in gatherInformation
    genomeID = int(linePar[1].split('|')[1])
IndexError: list index out of range
Staring Step 7 - EMAL POST\n\n
Reading in information...
Traceback (most recent call last):
  File "/home/v/EzMap/tools/EMAL/EMAL-Post.py", line 200, in <module>
    processCSV(inputFile)
  File "/home/v/EzMap/tools/EMAL/EMAL-Post.py", line 72, in processCSV
    with open(file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/v/EzMap/Output1/5-RelativeAbundanceEstimation/EzMapTest.gra'
Gathering Step 1 Results...
Gathering Step 2 Results...
Gathering Step 3 Results...
Gathering Step 4 Results...
Gathering Step 5 Results...
Traceback (most recent call last):
  File "/home/v/EzMap/Scripts/gatherResults.py", line 422, in <module>
    taxonomyLevels = emalInfo[0]
IndexError: list index out of range"

**Comment by kyle-lk** [comment]
also this problem. nobody want to fix this problem. another pipleline just for publish....
